Add type annotations and small fixes
jorio/rsrcdump pull request #1
Opened 2022-06-17 20:25 UTC by CoolCat467

This pull request aims to add type annotations to everything.
Other than type annotations, removes one unneeded F string, changes a few unused count variables to `_`, adds a few type assertions so my type checker doesn't get mad, makes rsrcdump/packutils.py `Unpacker` init argument `offset` actually do something, changes things like
```python
def func(say: str, is_cat: bool=False) -> str:
    if is_cat:
        return f'Cat says: {say}'
    else:
        return f'Person says: {say}'
```
to
```python
def func(say: str, is_cat: bool=False) -> str:
    if is_cat:
        return f'Cat says: {say}'
    return f'Person says: {say}'
```
, and changes
```python
...
with open(outpath + "/index.json", 'w') as file:
...
```
to
```python
...
with open(outpath + "/index.json", 'w', encoding='utf-8') as file:
...
```

2022-06-17 22:04 UTC, jorio requested changes
Thank you for your PR! Here's my feedback:

- Let's use PEP 585 (built-in hints for dict, list, tuple) and PEP 604 (pipe notation in lieu of Union). This requires bumping the Python version floor to 3.10 but I'm cool with that.
- Attributes instead of `__slots__`
- I prefer `Any` over a jumbo union for the return value of ResourceConverter.convert
- Don't abort read_pict_bits if palette is None — RGB pixmaps don't define a palette. Such PICTs exist in Nanosaur for example.

2022-06-17 22:04 UTC, jorio commented on rsrcdump/packutils.py
> +    def commit(self, value: Union[int, bytes, str]) -> None:
Let's make `value` an `Any` to match the signature of `struct.pack`.
```suggestion
    def commit(self, value: Any) -> None:
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/pict.py
> +                 'rowbytes', 'pixelsize')
```suggestion
    rowbytes: int
    pixelsize: int
    frame_t: int
    frame_l: int
    frame_b: int
    frame_r: int
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/pict.py
> +        return self.frame_r - self.frame_l# type: ignore
"type: ignore" won't be necessary if we use the field notation above.

```suggestion
        return self.frame_r - self.frame_l
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/pict.py
> +        return self.frame_b - self.frame_t# type: ignore
```suggestion
        return self.frame_b - self.frame_t
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/pict.py
> +        return (self.frame_t, self.frame_l, self.frame_b, self.frame_r)# type: ignore
```suggestion
    def frame_rect(self) -> tuple[int, int, int, int]:
        return (self.frame_t, self.frame_l, self.frame_b, self.frame_r)
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/pict.py
> +        return 8 * self.rowbytes // self.pixelsize# type: ignore
```suggestion
        return 8 * self.rowbytes // self.pixelsize
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/pict.py
> +def rect_dims(rect_tuple: Tuple[int, int, int, int]) -> Tuple[int, int]:
```suggestion
def rect_dims(rect_tuple: tuple[int, int, int, int]) -> tuple[int, int]:
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/pict.py
> +def unpack_bits(slice: bytes, packfmt: str, rowbytes: int) -> List[int]:
```suggestion
def unpack_bits(slice: bytes, packfmt: str, rowbytes: int) -> list[int]:
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/pict.py
> +def unpack_all_rows(u: Unpacker, packfmt: str, numrows: int, rowbytes: int) -> List[int]:
```suggestion
def unpack_all_rows(u: Unpacker, packfmt: str, numrows: int, rowbytes: int) -> list[int]:
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/pict.py
> +def unpack0(u: Unpacker, pmh: Pixmap, palette: List[bytes]) -> bytes: # w: int, h: int, rowbytes: bytes, palette: List[bytes]) -> bytes:
Let's get rid of this obsolete comment while we're here.
```suggestion
def unpack0(u: Unpacker, pmh: Pixmap, palette: list[bytes]) -> bytes:
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/adf.py
> +def unpack_adf(adf_data: bytes) -> Dict[int, bytes]:
```suggestion
def unpack_adf(adf_data: bytes) -> dict[int, bytes]:
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/adf.py
> +def pack_adf(adf_entries: Dict[int, bytes]) -> bytes:
```suggestion
def pack_adf(adf_entries: dict[int, bytes]) -> bytes:
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/extract.py
> +                         quiet: bool=False) -> None:
```suggestion
def extract_resource_map(res_map: dict[bytes, dict[int, Resource]],
                         outpath: str,
                         include_types: list[bytes]=[],
                         exclude_types: list[bytes]=[],
                         quiet: bool=False) -> None:
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/extract.py
> +            wrapper: Dict[str, Union[int, str]] = {}
```suggestion
            wrapper: dict[str, Any] = {}
```
I'd like to avoid maintaining a complex signature for all types that can be returned by the ResourceConverters.
For example, StringListConverter returns a list[str], which isn't covered by Union[int,str].
So, how about just using dict[str, Any]?

2022-06-17 22:04 UTC, jorio commented on rsrcdump/extract.py
> +    J: Dict[str, Dict[int, Dict[str, Union[int, str]]]] = {}
```suggestion
    J: dict[str, dict[int, dict[str, Any]]] = {}
```
See below for an explanation

2022-06-17 22:04 UTC, jorio commented on rsrcdump/packutils.py
> +    def unpack(self, fmt: str) -> Tuple:
```suggestion
    def unpack(self, fmt: str) -> tuple:
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/pict.py
> +def read_colortable(u: Unpacker) -> List[bytes]:
```suggestion
def read_colortable(u: Unpacker) -> list[bytes]:
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/pict.py
> +def read_pict_bits(u: Unpacker, opcode: int) -> Tuple[Tuple[int, int, int, int], bytes]:
```suggestion
def read_pict_bits(u: Unpacker, opcode: int) -> tuple[tuple[int, int, int, int], bytes]:
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/pict.py
> +def convert_pict_to_image(data: bytes) -> Tuple[int, int, bytes]:
```suggestion
def convert_pict_to_image(data: bytes) -> tuple[int, int, bytes]:
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/pict.py
> +def convert_cicn_to_image(data: bytes) -> Tuple[int, int, bytes]:
```suggestion
def convert_cicn_to_image(data: bytes) -> tuple[int, int, bytes]:
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/pict.py
> +def convert_ppat_to_image(data: bytes) -> Tuple[int, int, bytes]:
```suggestion
def convert_ppat_to_image(data: bytes) -> tuple[int, int, bytes]:
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/pict.py
> +def convert_sicn_to_image(data: bytes) -> Tuple[int, int, bytes]:
```suggestion
def convert_sicn_to_image(data: bytes) -> tuple[int, int, bytes]:
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resconverters.py
> +    __slots__ = ('fmt', 'record_length', 'field_names', 'is_list')
```suggestion
    fmt: str
    record_length: int
    field_names: list[str]
    is_list: bool

```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resconverters.py
> +                res_map: Dict[bytes, Dict[int, Resource]]) -> Union[List[Dict[str, bytes]], Dict[str, bytes]]:
```suggestion
                res_map: dict[bytes, dict[int, Resource]]) -> list[dict[str, bytes]] | dict[str, bytes]:
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resconverters.py
> +    __slots__: Tuple = tuple()
```suggestion
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resconverters.py
> +    __slots__: Tuple = tuple()
```suggestion
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/packutils.py
> +    def unpack_pstr(self, decode: bool=True) -> Union[str, bytes]:
Since I'm open to bumping the Python version floor, how about this?
```suggestion
    def unpack_pstr(self, decode: bool=True) -> str | bytes:
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/pict.py
> +def read_bitmap_or_pixmap(u: Unpacker) -> Union[Pixmap, Bitmap]:
```suggestion
def read_bitmap_or_pixmap(u: Unpacker) -> Bitmap | Pixmap:
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/pict.py
> +def read_pixmap_image_data(u: Unpacker, pmh: Union[Bitmap, Pixmap], palette: List[bytes]) -> bytes:
```suggestion
def read_pixmap_image_data(u: Unpacker, pmh: Bitmap | Pixmap, palette: list[bytes]) -> bytes:
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resconverters.py
> +    def convert(self, res: Resource, res_map: Dict[bytes, Dict[int, Resource]]) -> Any:
```suggestion
    def convert(self, res: Resource, res_map: dict[bytes, dict[int, Resource]]) -> Any:
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resconverters.py
> +from typing import Any, Callable, Dict, List, Tuple, Union
```suggestion
from typing import Any, Callable
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resconverters.py
> +    def parse_record(self, data: bytes, offset: int) -> Dict[str, bytes]:
```suggestion
    def parse_record(self, data: bytes, offset: int) -> dict[str, bytes]:
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resconverters.py
> +    __slots__: Tuple = tuple()
```suggestion
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resconverters.py
> +    __slots__: Tuple = tuple()
```suggestion
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resconverters.py
> +                res_map: Dict[bytes, Dict[int, Resource]]) -> List[bytes]:
```suggestion
                res_map: dict[bytes, dict[int, Resource]]) -> list[bytes]:
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resconverters.py
> +                res_map: Dict[bytes, Dict[int, Resource]]) -> bytes:
```suggestion
                res_map: dict[bytes, dict[int, Resource]]) -> bytes:
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resconverters.py
> +    __slots__: Tuple = tuple()
```suggestion
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resconverters.py
> +                res_map: Dict[bytes, Dict[int, Resource]]) -> bytes:
```suggestion
                res_map: dict[bytes, dict[int, Resource]]) -> bytes:
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resconverters.py
> +    __slots__: Tuple = tuple()
```suggestion
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resconverters.py
> +                res_map: Dict[bytes, Dict[int, Resource]]) -> bytes:
```suggestion
                res_map: dict[bytes, dict[int, Resource]]) -> bytes:
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resconverters.py
> +    __slots__: Tuple = tuple()
```suggestion
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resconverters.py
> +                res_map: Dict[bytes, Dict[int, Resource]]) -> bytes:
```suggestion
                res_map: dict[bytes, dict[int, Resource]]) -> bytes:
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resconverters.py
> +    __slots__: Tuple = tuple()
```suggestion
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resconverters.py
> +                res_map: Dict[bytes, Dict[int, Resource]]) -> bytes:
```suggestion
                res_map: dict[bytes, dict[int, Resource]]) -> bytes:
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resconverters.py
> +    __slots__: Tuple = tuple()
```suggestion
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resconverters.py
> +                res_map: Dict[bytes, Dict[int, Resource]]) -> bytes:
```suggestion
                res_map: dict[bytes, dict[int, Resource]]) -> bytes:
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resconverters.py
> +    __slots__: Tuple = tuple()
```suggestion
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resconverters.py
> +                res_map: Dict[bytes, Dict[int, Resource]]) -> List[Dict[str, Union[str, bytes]]]:
unpack_pstr is guaranteed to return a str in this case
```suggestion
                res_map: dict[bytes, dict[int, Resource]]) -> list[dict[str, str]]:
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resconverters.py
> +    __slots__ = ('preprocess',)
```suggestion
    preprocess: Callable[[bytes], bytes] | None

```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resconverters.py
> +    def convert(self, res: Resource, res_map: Dict[bytes, Dict[int, Resource]]) -> bytes:
```suggestion
    def convert(self, res: Resource, res_map: dict[bytes, dict[int, Resource]]) -> bytes:
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resconverters.py
> +    __slots__: Tuple = tuple()
```suggestion
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resconverters.py
> +                res_map: Dict[bytes, Dict[int, Resource]]) -> bytes:
```suggestion
                res_map: dict[bytes, dict[int, Resource]]) -> bytes:
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resconverters.py
> +
```suggestion
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resfork.py
> +
```suggestion
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resfork.py
> +def unpack_resfork(fork: bytes) -> Dict[bytes, Dict[int, Resource]]:
```suggestion
def unpack_resfork(fork: bytes) -> dict[bytes, dict[int, Resource]]:
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resfork.py
> +    res_map: Dict[bytes, Dict[int, Resource]] = {}
```suggestion
    res_map: dict[bytes, dict[int, Resource]] = {}
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resfork.py
> +def pack_resfork(res_map: Dict[bytes, Dict[str, Resource]]) -> bytes:
```suggestion
def pack_resfork(res_map: dict[bytes, dict[str, Resource]]) -> bytes:
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/adf.py
> +
```suggestion
from typing import Final

```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/extract.py
> +
```suggestion
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/icons.py
> +
```suggestion
from typing import Callable

```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/packutils.py
> +from io import BytesIO
```suggestion
from io import BytesIO
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/pict.py
> +
```suggestion
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/pict.py
> +    if opcode in [0x0091, 0x009b] or palette is None:
```suggestion
    if opcode in [0x0091, 0x009b]:
```
There's no palette with opcode 009A (RGB pixmap)

2022-06-17 22:04 UTC, jorio commented on rsrcdump/pict.py
> +        raise ValueError('Expected Bitmap from read_bitmap_or_pixmap')
```suggestion
        raise ValueError('Expected Pixmap from read_bitmap_or_pixmap')
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/png.py
> +from typing import List, Optional
```suggestion
from typing import Optional
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resconverters.py
> +    def __init__(self, separate_file: str=None) -> None:
```suggestion
    separate_file: str

    def __init__(self, separate_file: str="") -> None:
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resconverters.py
> +                res_map: Dict[bytes, Dict[int, Resource]]) -> bytes:
```suggestion
                res_map: dict[bytes, dict[int, Resource]]) -> bytes:
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resconverters.py
> +                res_map: Dict[bytes, Dict[int, Resource]]) -> str:
```suggestion
                res_map: dict[bytes, dict[int, Resource]]) -> str:
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resconverters.py
>              bw_icon = None
For consistency
```suggestion
            bw_icon = b''
```

2022-06-17 22:04 UTC, jorio commented on rsrcdump/resconverters.py
> +##            bw_mask = None
```suggestion
```

2022-06-18 00:08 UTC, CoolCat467 commented on rsrcdump/extract.py
> +            wrapper: Dict[str, Union[int, str]] = {}
I guess that works

2022-06-18 10:15 UTC, merged

2022-06-18 10:18 UTC, jorio commented
Merged. Thank you for your contribution!

2022-06-18 15:56 UTC, CoolCat467 commented
You are welcome!